gateway:
  address: "amqp://guest:guest@rabbitmq:5672/"
heartbeat:
  host: "egg_of_life"
  port: 7777
  interval: 5
log:
  level: "development"
filter:
  year:
    from: 2024
    to: 2025
  businessHours:
    from: 6
    to: 23
  totalAmountThreshold: 75.0
