port: 8080
healthcheck:
  port: 8081
heartbeat:
  host: "egg_of_life"
  port: 7777
  interval: 1
middleware:
  address: "amqp://guest:guest@rabbitmq:5672/"
log:
  level: "development"
receiving:
  timeout: 10
