services:
  gateway:
    instances: 2
  controller:
    instances: 1
  filter:
    instances: 2
   #  tags: "poison low_prob"
  group_by:
    instances: 2
   #  tags: "poison low_prob"
  reducer:
    instances: 2
   #  tags: "poison low_prob"
  aggregator:
    instances: 3
  joiner:
    instances: 2
    # tags: "poison low_prob"
  client:
    instances: 4
