services:
  gateway:
    instances: 1
  controller:
    instances: 1
  filter:
    instances: 2
    # tags: "poison low_prob"
  group_by:
    instances: 2
  reducer:
    instances: 2
  aggregator:
    instances: 4
  joiner:
    instances: 2
  client:
    instances: 10
