services:
  gateway:
    instances: 2
  controller:
    instances: 1
  filter:
    instances: 2
    # tags: "poison mid_prob"
  group_by:
    instances: 2
    # tags: "poison mid_prob"
  reducer:
    instances: 2
    # tags: "poison mid_prob"
  aggregator:
    instances: 1
  joiner:
    instances: 2
  client:
    instances: 4
