port: 8080
middleware:
  address: "amqp://guest:guest@rabbitmq:5672/"
heartbeat:
  host: "egg_of_life"
  port: 7777
  interval: 200
log:
  level: "development"
max:
  clients: 100
  unacked_counters: 5000
storage:
  path: "storage"
