gateway:
  address: "guest:guest@localhost:5672"
log:
  level: "DEBUG"
queues:
  store_tpv_queue: "store_tpv"
  transaction_counted_queue: "transaction_counted"
  transaction_sum_queue: "transaction_sum"
  user_transactions_queu: "user_transactions"