gateway:
  address: "guest:guest@localhost:5672"
log:
  level: "DEBUG"
queues:
  store_tpv_queue: "store_tpv"
  transaction_counted_queue: "transaction_counted"
  transaction_sum_queue: "transaction_sum"
  user_transactions_queue: "user_transactions"
  gateway_controller_queue: "node_connections"
aggregator_queues:
  joined_most_profits_transactions_queue: "joined_most_profits_transactions"
  joined_best_selling_transactions_queue: "joined_best_selling_transactions"
  joined_stores_tpv_queue: "joined_stores_tpv"
  joined_user_transactions_queue: "joined_user_transactions"
exchanges:
  gateway_controller_exchange: "finish_exchange"
  finish_routing_key: "joiner"